/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BillController;
import Controller.InBill;
import Controller.UserController;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author Admin
 */
public class HomJPanel extends javax.swing.JPanel {
    static String k="";
    /**
     * Creates new form HomJPanel
     */
    public HomJPanel() {
        initComponents();
        if(k.equals("2")){
            jButtonManager.setVisible(false);
        }
        jLabelDate.setText(LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate = new javax.swing.JLabel();
        jButtonManager = new javax.swing.JButton();
        jButtonAdjustAccount = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));
        setPreferredSize(new java.awt.Dimension(1500, 800));

        jLabelDate.setBackground(new java.awt.Color(102, 255, 255));
        jLabelDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDate.setOpaque(true);

        jButtonManager.setBackground(java.awt.Color.lightGray);
        jButtonManager.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_staff_40px_1.png"))); // NOI18N
        jButtonManager.setText("Quản lí nhân viên ");
        jButtonManager.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 5, 0, new java.awt.Color(51, 51, 51)));
        jButtonManager.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerActionPerformed(evt);
            }
        });

        jButtonAdjustAccount.setBackground(java.awt.Color.lightGray);
        jButtonAdjustAccount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonAdjustAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_update_40px_1.png"))); // NOI18N
        jButtonAdjustAccount.setText("Cập nhật tài khoản ");
        jButtonAdjustAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 5, 0, new java.awt.Color(51, 51, 51)));
        jButtonAdjustAccount.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonAdjustAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdjustAccountActionPerformed(evt);
            }
        });

        jButtonLogOut.setBackground(java.awt.Color.lightGray);
        jButtonLogOut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_exit_40px_2.png"))); // NOI18N
        jButtonLogOut.setText("Đăng xuất ");
        jButtonLogOut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 5, 0, new java.awt.Color(51, 51, 51)));
        jButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdjustAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManager, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButtonManager, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonAdjustAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerActionPerformed
        removeAll();
        setLayout(new BorderLayout());
        add(new AccountJPanel());
        validate();
        repaint();
    }//GEN-LAST:event_jButtonManagerActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
//        if(BillController.getCountLastIbID() > 0){
//            MainFrame.lastIB.idUser = UserController.findID(MainFrame.userName);
//            MainFrame.lastIB.ibDate = new SimpleDateFormat("YYYY-MM-dd").format(new Date());
//            BillController.initInBillWithUserDate(MainFrame.lastIB);
//            BillController.addInBill(new InBill());
//        }
        System.exit(0);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAdjustAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdjustAccountActionPerformed
        UpdateAccount updateAccount=new UpdateAccount();
        updateAccount.setVisible(true);
    }//GEN-LAST:event_jButtonAdjustAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdjustAccount;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonManager;
    private javax.swing.JLabel jLabelDate;
    // End of variables declaration//GEN-END:variables
}
